"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TenXBank__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var TenXBank__factory_1 = require("./TenXBank__factory");
Object.defineProperty(exports, "TenXBank__factory", { enumerable: true, get: function () { return TenXBank__factory_1.TenXBank__factory; } });
